-- Auto generated by the wau-scanner v0

--- river_xkb_config_v1
-- @module river_xkb_config_v1

-- SPDX-FileCopyrightText: © 2026 Isaac Freund
-- SPDX-License-Identifier: MIT
-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to
-- deal in the Software without restriction, including without limitation the
-- rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
-- sell copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:
-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
-- FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
-- IN THE SOFTWARE.
return function(wau)

local interfaces = {
    "river_xkb_config_v1",
    "river_xkb_keymap_v1",
    "river_xkb_keyboard_v1",
}

for _, iface in ipairs(interfaces) do
    wau[iface] = wau.wl_interface.new()
end

--- xkb config global interface
--
-- Global interface for configuring xkb devices.
-- This global should only be advertised if river_input_manager_v1 is
-- advertised as well.
-- @type river_xkb_config_v1
wau.river_xkb_config_v1:init {
    name = "river_xkb_config_v1",
    version = 1,
    methods = {
        --- stop sending events
        --
        -- This request indicates that the client no longer wishes to receive
        -- events on this object.
        -- The Wayland protocol is asynchronous, which means the server may send
        -- further events until the stop request is processed. The client must wait
        -- for a river_xkb_config_v1.finished event before destroying this object.
        -- @function river_xkb_config_v1:stop
        -- @treturn river_xkb_config_v1 self
        {
            name = "stop",
            signature = "",
            types = { },
        },
        --- destroy the river_xkb_config_v1 object
        --
        -- This request should be called after the finished event has been received
        -- to complete destruction of the object.
        -- It is a protocol error to make this request before the finished event
        -- has been received.
        -- If a client wishes to destroy this object it should send a
        -- river_xkb_config_v1.stop request and wait for a
        -- river_xkb_config_v1.finished event. Once the finished event is received
        -- it is safe to destroy this object and any other objects created through
        -- this interface.
        -- @function river_xkb_config_v1:destroy
        -- @treturn river_xkb_config_v1 self
        {
            name = "destroy",
            signature = "",
            types = { },
            type = "destructor"
        },
        --- create a keymap object
        --
        -- The server must be able to mmap the fd with MAP_PRIVATE.
        -- The server will fstat the fd to obtain the size of the keymap.
        -- The client must not modify the contents of the fd after making this request.
        -- The client should seal the fd with fcntl.
        -- @function river_xkb_config_v1:create_keymap
        -- @treturn river_xkb_keymap_v1
        -- @tparam fd fd
        -- @tparam uint format
        {
            name = "create_keymap",
            signature = "nhu",
            types = { wau.river_xkb_keymap_v1, 0, 0, },
        },
    },
    events = {
        --- the server has finished with the object
        --
        -- This event indicates that the server will send no further events on this
        -- object. The client should destroy the object. See
        -- river_xkb_config_v1.destroy for more information.
        -- @event river_xkb_config_v1:finished
        {
            name = "finished",
            signature = "",
            types = { },
        },
        --- new xkb keyboard
        --
        -- A new xkbcommon keyboard has been created. Not every
        -- river_input_device_v1 is necessarily an xkbcommon keyboard as well.
        -- @event river_xkb_config_v1:xkb_keyboard
        -- @tparam river_xkb_keyboard_v1 id
        {
            name = "xkb_keyboard",
            signature = "n",
            types = { wau.river_xkb_keyboard_v1, },
        },
    },
    enums = {
        --- error
        -- @enum river_xkb_config_v1.Error
        -- @param INVALID_DESTROY 0
        -- @param INVALID_FORMAT 1
        ["error"] = {
            ["invalid_destroy"] = 0,
            ["invalid_format"] = 1,
        },
        --- keymap_format
        -- @enum river_xkb_config_v1.KeymapFormat
        -- @param TEXT_V1 1 XKB_KEYMAP_FORMAT_TEXT_V1
        -- @param TEXT_V2 2 XKB_KEYMAP_FORMAT_TEXT_V2
        ["keymap_format"] = {
            ["text_v1"] = 1,
            ["text_v2"] = 2,
        },
    },
    methods_opcode = {
        ["stop"] = 0,
        ["destroy"] = 1,
        ["create_keymap"] = 2,
    },
}

--- xkbcommon keymap
--
-- This object is the result of attempting to create an xkbcommon keymap.
-- @type river_xkb_keymap_v1
wau.river_xkb_keymap_v1:init {
    name = "river_xkb_keymap_v1",
    version = 1,
    methods = {
        --- destroy the keymap object
        --
        -- This request indicates that the client will no longer use the keymap
        -- object and that it may be safely destroyed.
        -- @function river_xkb_keymap_v1:destroy
        -- @treturn river_xkb_keymap_v1 self
        {
            name = "destroy",
            signature = "",
            types = { },
            type = "destructor"
        },
    },
    events = {
        --- keymap creation succeeded
        --
        -- The keymap object was successfully created and may be used with the
        -- river_xkb_keyboard_v1.set_keymap request.
        -- @event river_xkb_keymap_v1:success
        {
            name = "success",
            signature = "",
            types = { },
        },
        --- keymap creation failed
        --
        -- The compositor failed to create a keymap from the given parameters.
        -- It is a protocol error to use this keymap object with
        -- river_xkb_keyboard_v1.set_keymap.
        -- @event river_xkb_keymap_v1:failure
        -- @tparam string error_msg
        {
            name = "failure",
            signature = "s",
            types = { 0, },
        },
    },
    enums = {
    },
    methods_opcode = {
        ["destroy"] = 0,
    },
}

--- xkbcommon keyboard device
--
-- This object represent a physical keyboard which has its configuration and
-- state managed by xkbcommon.
-- @type river_xkb_keyboard_v1
wau.river_xkb_keyboard_v1:init {
    name = "river_xkb_keyboard_v1",
    version = 1,
    methods = {
        --- destroy the xkb keyboard object
        --
        -- This request indicates that the client will no longer use the keyboard
        -- object and that it may be safely destroyed.
        -- @function river_xkb_keyboard_v1:destroy
        -- @treturn river_xkb_keyboard_v1 self
        {
            name = "destroy",
            signature = "",
            types = { },
            type = "destructor"
        },
        --- set the keymap
        --
        -- Set the keymap for the keyboard.
        -- Setting a keymap will reset all layout/modifier state.
        -- It is a protocol error to pass a keymap object for which the
        -- river_xkb_keymap_v1.success event was not received.
        -- @function river_xkb_keyboard_v1:set_keymap
        -- @tparam river_xkb_keymap_v1 keymap
        -- @treturn river_xkb_keyboard_v1 self
        {
            name = "set_keymap",
            signature = "o",
            types = { wau.river_xkb_keymap_v1, },
        },
        --- set the active layout by index
        --
        -- Set the active layout for the keyboard's keymap. Has no effect if the
        -- layout index is out of bounds for the current keymap.
        -- @function river_xkb_keyboard_v1:set_layout_by_index
        -- @tparam int index
        -- @treturn river_xkb_keyboard_v1 self
        {
            name = "set_layout_by_index",
            signature = "i",
            types = { 0, },
        },
        --- set the active layout by name
        --
        -- Set the active layout for the keyboard's keymap. Has no effect if there
        -- is no layout with the give name for the keyboard's keymap.
        -- @function river_xkb_keyboard_v1:set_layout_by_name
        -- @tparam string name
        -- @treturn river_xkb_keyboard_v1 self
        {
            name = "set_layout_by_name",
            signature = "s",
            types = { 0, },
        },
        --- enable capslock
        --
        -- Enable capslock for the keyboard.
        -- @function river_xkb_keyboard_v1:capslock_enable
        -- @treturn river_xkb_keyboard_v1 self
        {
            name = "capslock_enable",
            signature = "",
            types = { },
        },
        --- disable capslock
        --
        -- Disable capslock for the keyboard.
        -- @function river_xkb_keyboard_v1:capslock_disable
        -- @treturn river_xkb_keyboard_v1 self
        {
            name = "capslock_disable",
            signature = "",
            types = { },
        },
        --- enable numlock
        --
        -- Enable numlock for the keyboard.
        -- @function river_xkb_keyboard_v1:numlock_enable
        -- @treturn river_xkb_keyboard_v1 self
        {
            name = "numlock_enable",
            signature = "",
            types = { },
        },
        --- disable numlock
        --
        -- Disable numlock for the keyboard.
        -- @function river_xkb_keyboard_v1:numlock_disable
        -- @treturn river_xkb_keyboard_v1 self
        {
            name = "numlock_disable",
            signature = "",
            types = { },
        },
    },
    events = {
        --- the xkb keyboard is removed
        --
        -- This event indicates that the xkb keyboard has been removed.
        -- The server will send no further events on this object and ignore any
        -- request (other than river_xkb_keyboard_v1.destroy) made after this event
        -- is sent. The client should destroy this object with the
        -- river_xkb_keyboard_v1.destroy request to free up resources.
        -- @event river_xkb_keyboard_v1:removed
        {
            name = "removed",
            signature = "",
            types = { },
        },
        --- corresponding river input device
        --
        -- The river_input_device_v1 corresponding to this xkb keyboard. This event
        -- will always be the first event sent on the river_xkb_keyboard_v1 object,
        -- and it will be sent exactly once.
        -- @event river_xkb_keyboard_v1:input_device
        -- @tparam river_input_device_v1 device
        {
            name = "input_device",
            signature = "o",
            types = { wau.river_input_device_v1, },
        },
        --- currently active layout
        --
        -- The currently active layout index and name. The name arg may be null if
        -- the active layout does not have a name.
        -- This event is sent once when the river_xkb_keyboard_v1 is created and
        -- again whenever the layout changes.
        -- @event river_xkb_keyboard_v1:layout
        -- @tparam uint index
        -- @tparam string name
        {
            name = "layout",
            signature = "u?s",
            types = { 0, 0, },
        },
        --- capslock is currently enabled
        --
        -- Capslock is currently enabled for the keyboard.
        -- This event is sent once when the river_xkb_keyboard_v1 is created and
        -- again whenever the capslock state changes.
        -- @event river_xkb_keyboard_v1:capslock_enabled
        {
            name = "capslock_enabled",
            signature = "",
            types = { },
        },
        --- capslock is currently disabled
        --
        -- Capslock is currently disabled for the keyboard.
        -- This event is sent once when the river_xkb_keyboard_v1 is created and
        -- again whenever the capslock state changes.
        -- @event river_xkb_keyboard_v1:capslock_disabled
        {
            name = "capslock_disabled",
            signature = "",
            types = { },
        },
        --- numlock is currently enabled
        --
        -- Numlock is currently enabled for the keyboard.
        -- This event is sent once when the river_xkb_keyboard_v1 is created and
        -- again whenever the numlock state changes.
        -- @event river_xkb_keyboard_v1:numlock_enabled
        {
            name = "numlock_enabled",
            signature = "",
            types = { },
        },
        --- numlock is currently disabled
        --
        -- Numlock is currently disabled for the keyboard.
        -- This event is sent once when the river_xkb_keyboard_v1 is created and
        -- again whenever the numlock state changes.
        -- @event river_xkb_keyboard_v1:numlock_disabled
        {
            name = "numlock_disabled",
            signature = "",
            types = { },
        },
    },
    enums = {
        --- error
        -- @enum river_xkb_keyboard_v1.Error
        -- @param INVALID_KEYMAP 0
        ["error"] = {
            ["invalid_keymap"] = 0,
        },
    },
    methods_opcode = {
        ["destroy"] = 0,
        ["set_keymap"] = 1,
        ["set_layout_by_index"] = 2,
        ["set_layout_by_name"] = 3,
        ["capslock_enable"] = 4,
        ["capslock_disable"] = 5,
        ["numlock_enable"] = 6,
        ["numlock_disable"] = 7,
    },
}

end
