-- Auto generated by the wau-scanner v0

--- river_input_management_v1
-- @module river_input_management_v1

-- SPDX-FileCopyrightText: © 2025 Isaac Freund
-- SPDX-License-Identifier: MIT
-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to
-- deal in the Software without restriction, including without limitation the
-- rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
-- sell copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:
-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
-- FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
-- IN THE SOFTWARE.
return function(wau)

local interfaces = {
    "river_input_manager_v1",
    "river_input_device_v1",
}

for _, iface in ipairs(interfaces) do
    wau[iface] = wau.wl_interface.new()
end

--- input manager global interface
--
-- Input manager global interface.
-- @type river_input_manager_v1
wau.river_input_manager_v1:init {
    name = "river_input_manager_v1",
    version = 1,
    methods = {
        --- stop sending events
        --
        -- This request indicates that the client no longer wishes to receive
        -- events on this object.
        -- The Wayland protocol is asynchronous, which means the server may send
        -- further events until the stop request is processed. The client must wait
        -- for a river_input_manager_v1.finished event before destroying this
        -- object.
        -- @function river_input_manager_v1:stop
        -- @treturn river_input_manager_v1 self
        {
            name = "stop",
            signature = "",
            types = { },
        },
        --- destroy the river_input_manager_v1 object
        --
        -- This request should be called after the finished event has been received
        -- to complete destruction of the object.
        -- It is a protocol error to make this request before the finished event
        -- has been received.
        -- If a client wishes to destroy this object it should send a
        -- river_input_manager_v1.stop request and wait for a
        -- river_input_manager_v1.finished event. Once the finished event is
        -- received it is safe to destroy this object and any other objects created
        -- through this interface.
        -- @function river_input_manager_v1:destroy
        -- @treturn river_input_manager_v1 self
        {
            name = "destroy",
            signature = "",
            types = { },
            type = "destructor"
        },
        --- create a new seat
        --
        -- Create a new seat with the given name. Has no effect if a seat with the
        -- given name already exists.
        -- The default seat with name "default" always exists and does not need to
        -- be explicitly created.
        -- @function river_input_manager_v1:create_seat
        -- @tparam string name
        -- @treturn river_input_manager_v1 self
        {
            name = "create_seat",
            signature = "s",
            types = { 0, },
        },
        --- destroy a seat
        --
        -- Destroy the seat with the given name. Has no effect if a seat with the
        -- given name does not exist.
        -- The default seat with name "default" cannot be destroyed and attempting
        -- to destroy it will have no effect.
        -- Any input devices assigned to the destroyed seat at the time of
        -- destruction are assigned to the default seat.
        -- @function river_input_manager_v1:destroy_seat
        -- @tparam string name
        -- @treturn river_input_manager_v1 self
        {
            name = "destroy_seat",
            signature = "s",
            types = { 0, },
        },
    },
    events = {
        --- the server has finished with the input manager
        --
        -- This event indicates that the server will send no further events on this
        -- object. The client should destroy the object. See
        -- river_input_manager_v1.destroy for more information.
        -- @event river_input_manager_v1:finished
        {
            name = "finished",
            signature = "",
            types = { },
        },
        --- new input device
        --
        -- A new input device has been created.
        -- @event river_input_manager_v1:input_device
        -- @tparam river_input_device_v1 id
        {
            name = "input_device",
            signature = "n",
            types = { wau.river_input_device_v1, },
        },
    },
    enums = {
        --- error
        -- @enum river_input_manager_v1.Error
        -- @param INVALID_DESTROY 0
        ["error"] = {
            ["invalid_destroy"] = 0,
        },
    },
    methods_opcode = {
        ["stop"] = 0,
        ["destroy"] = 1,
        ["create_seat"] = 2,
        ["destroy_seat"] = 3,
    },
}

--- an input device
--
-- An input device represents a physical keyboard, mouse, touchscreen, or
-- drawing tablet tool. It is assigned to exactly one seat at a time.
-- By default, all input devices are assigned to the default seat.
-- @type river_input_device_v1
wau.river_input_device_v1:init {
    name = "river_input_device_v1",
    version = 1,
    methods = {
        --- destroy the input device object
        --
        -- This request indicates that the client will no longer use the input
        -- device object and that it may be safely destroyed.
        -- @function river_input_device_v1:destroy
        -- @treturn river_input_device_v1 self
        {
            name = "destroy",
            signature = "",
            types = { },
            type = "destructor"
        },
        --- assign the input device to a seat
        --
        -- Assign the input device to a seat. All input devices not explicitly
        -- assigned to a seat are considered assigned to the default seat.
        -- Has no effect if a seat with the given name does not exist.
        -- @function river_input_device_v1:assign_to_seat
        -- @tparam string name name of the seat
        -- @treturn river_input_device_v1 self
        {
            name = "assign_to_seat",
            signature = "s",
            types = { 0, },
        },
        --- set keyboard repeat rate and delay
        --
        -- Set repeat rate and delay for a keyboard input device. Has no effect if
        -- the device is not a keyboard.
        -- Negative values for either rate or delay are illegal. A rate of zero
        -- will disable any repeating (regardless of the value of delay).
        -- @function river_input_device_v1:set_repeat_info
        -- @tparam int rate rate in key repeats per second
        -- @tparam int delay delay in milliseconds
        -- @treturn river_input_device_v1 self
        {
            name = "set_repeat_info",
            signature = "ii",
            types = { 0, 0, },
        },
        --- set scroll factor
        --
        -- Set the scroll factor for a pointer input device. Has no effect if the
        -- device is not a pointer.
        -- For example, a factor of 0.5 will make scrolling twice as slow while a
        -- factor of 3.0 will make scrolling 3 times as fast.
        -- Setting a scroll factor less than 0 is a protocol error.
        -- @function river_input_device_v1:set_scroll_factor
        -- @tparam fixed factor
        -- @treturn river_input_device_v1 self
        {
            name = "set_scroll_factor",
            signature = "f",
            types = { 0, },
        },
        --- map input device to the given output
        --
        -- Map the input device to the given output. Has no effect if the device is
        -- not a pointer, touch, or tablet device.
        -- If mapped to both an output and a rectangle, the rectangle has priority.
        -- Passing null clears an existing mapping.
        -- @function river_input_device_v1:map_to_output
        -- @tparam wl_output output
        -- @treturn river_input_device_v1 self
        {
            name = "map_to_output",
            signature = "?o",
            types = { wau.wl_output, },
        },
        --- map input device to the given rectangle
        --
        -- Map the input device to the given rectangle in the global compositor
        -- coordinate space. Has no effect if the device is not a pointer, touch,
        -- or tablet device.
        -- If mapped to both an output and a rectangle, the rectangle has priority.
        -- Width and height must be greater than or equal to 0.
        -- Passing 0 for width or height clears an existing mapping.
        -- @function river_input_device_v1:map_to_rectangle
        -- @tparam int x
        -- @tparam int y
        -- @tparam int width
        -- @tparam int height
        -- @treturn river_input_device_v1 self
        {
            name = "map_to_rectangle",
            signature = "iiii",
            types = { 0, 0, 0, 0, },
        },
    },
    events = {
        --- the input device is removed
        --
        -- This event indicates that the input device has been removed.
        -- The server will send no further events on this object and ignore any
        -- request (other than river_input_device_v1.destroy) made after this event is
        -- sent. The client should destroy this object with the
        -- river_input_device_v1.destroy request to free up resources.
        -- @event river_input_device_v1:removed
        {
            name = "removed",
            signature = "",
            types = { },
        },
        --- the type of the input device
        --
        -- The type of the input device. This event is sent once when the
        -- river_input_device_v1 object is created. The device type cannot
        -- change during the lifetime of the object.
        -- @event river_input_device_v1:type
        -- @tparam uint type
        {
            name = "type",
            signature = "u",
            types = { 0, },
        },
        --- the name of the input device
        --
        -- The name of the input device. This event is sent once when the
        -- river_input_device_v1 object is created. The device name cannot
        -- change during the lifetime of the object.
        -- @event river_input_device_v1:name
        -- @tparam string name
        {
            name = "name",
            signature = "s",
            types = { 0, },
        },
    },
    enums = {
        --- error
        -- @enum river_input_device_v1.Error
        -- @param INVALID_REPEAT_INFO 0
        -- @param INVALID_SCROLL_FACTOR 1
        -- @param INVALID_MAP_TO_RECTANGLE 2
        ["error"] = {
            ["invalid_repeat_info"] = 0,
            ["invalid_scroll_factor"] = 1,
            ["invalid_map_to_rectangle"] = 2,
        },
        --- type
        -- @enum river_input_device_v1.Type
        -- @param KEYBOARD 0
        -- @param POINTER 1
        -- @param TOUCH 2
        -- @param TABLET 3
        ["type"] = {
            ["keyboard"] = 0,
            ["pointer"] = 1,
            ["touch"] = 2,
            ["tablet"] = 3,
        },
    },
    methods_opcode = {
        ["destroy"] = 0,
        ["assign_to_seat"] = 1,
        ["set_repeat_info"] = 2,
        ["set_scroll_factor"] = 3,
        ["map_to_output"] = 4,
        ["map_to_rectangle"] = 5,
    },
}

end
