-- Auto generated by the wau-scanner v0

--- river_libinput_config_v1
-- @module river_libinput_config_v1

-- SPDX-FileCopyrightText: © 2025 Isaac Freund
-- SPDX-License-Identifier: MIT
-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to
-- deal in the Software without restriction, including without limitation the
-- rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
-- sell copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:
-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
-- FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
-- IN THE SOFTWARE.
return function(wau)

local interfaces = {
    "river_libinput_config_v1",
    "river_libinput_device_v1",
    "river_libinput_accel_config_v1",
    "river_libinput_result_v1",
}

for _, iface in ipairs(interfaces) do
    wau[iface] = wau.wl_interface.new()
end

--- libinput config global interface
--
-- Global interface for configuring libinput devices. This global should
-- only be advertised if river_input_manager_v1 is advertised as well.
-- @type river_libinput_config_v1
wau.river_libinput_config_v1:init {
    name = "river_libinput_config_v1",
    version = 1,
    methods = {
        --- stop sending events
        --
        -- This request indicates that the client no longer wishes to receive
        -- events on this object.
        -- The Wayland protocol is asynchronous, which means the server may send
        -- further events until the stop request is processed. The client must wait
        -- for a river_libinput_config_v1.finished event before destroying this
        -- object.
        -- @function river_libinput_config_v1:stop
        -- @treturn river_libinput_config_v1 self
        {
            name = "stop",
            signature = "",
            types = { },
        },
        --- destroy the river_libinput_config_v1 object
        --
        -- This request should be called after the finished event has been received
        -- to complete destruction of the object.
        -- It is a protocol error to make this request before the finished event
        -- has been received.
        -- If a client wishes to destroy this object it should send a
        -- river_libinput_config_v1.stop request and wait for a
        -- river_libinput_config_v1.finished event. Once the finished event is
        -- received it is safe to destroy this object and any other objects created
        -- through this interface.
        -- @function river_libinput_config_v1:destroy
        -- @treturn river_libinput_config_v1 self
        {
            name = "destroy",
            signature = "",
            types = { },
            type = "destructor"
        },
        --- create a acceleration config
        --
        -- Create a acceleration config which can be applied
        -- with river_libinput_device_v1.apply_accel_config.
        -- @function river_libinput_config_v1:create_accel_config
        -- @treturn river_libinput_accel_config_v1
        -- @tparam uint profile
        {
            name = "create_accel_config",
            signature = "nu",
            types = { wau.river_libinput_accel_config_v1, 0, },
        },
    },
    events = {
        --- the server has finished with the object
        --
        -- This event indicates that the server will send no further events on this
        -- object. The client should destroy the object. See
        -- river_libinput_config_v1.destroy for more information.
        -- @event river_libinput_config_v1:finished
        {
            name = "finished",
            signature = "",
            types = { },
        },
        --- new libinput device
        --
        -- A new libinput device has been created. Not every river_input_device_v1
        -- is necessarily a libinput device as well.
        -- @event river_libinput_config_v1:libinput_device
        -- @tparam river_libinput_device_v1 id
        {
            name = "libinput_device",
            signature = "n",
            types = { wau.river_libinput_device_v1, },
        },
    },
    enums = {
        --- error
        -- @enum river_libinput_config_v1.Error
        -- @param INVALID_ARG 0 invalid enum value or similar
        -- @param INVALID_DESTROY 1
        ["error"] = {
            ["invalid_arg"] = 0,
            ["invalid_destroy"] = 1,
        },
    },
    methods_opcode = {
        ["stop"] = 0,
        ["destroy"] = 1,
        ["create_accel_config"] = 2,
    },
}

--- a libinput device
--
-- In general, *_support events will be sent exactly once directly after the
-- river_libinput_device_v1 is created. *_default events will be sent after
-- *_support events if the config option is supported, and *_current events
-- willl be sent after the *_default events and again whenever the config
-- option is changed.
-- @type river_libinput_device_v1
wau.river_libinput_device_v1:init {
    name = "river_libinput_device_v1",
    version = 1,
    methods = {
        --- destroy the libinput device object
        --
        -- This request indicates that the client will no longer use the input
        -- device object and that it may be safely destroyed.
        -- @function river_libinput_device_v1:destroy
        -- @treturn river_libinput_device_v1 self
        {
            name = "destroy",
            signature = "",
            types = { },
            type = "destructor"
        },
        --- set send events mode
        --
        -- Set the send events mode for the device.
        -- @function river_libinput_device_v1:set_send_events
        -- @treturn river_libinput_result_v1
        -- @tparam uint mode
        {
            name = "set_send_events",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- enable/disable tap-to-click
        --
        -- Configure tap-to-click on this device, with a default mapping of
        -- 1, 2, 3 finger tap mapping to left, right, middle click, respectively.
        -- @function river_libinput_device_v1:set_tap
        -- @treturn river_libinput_result_v1
        -- @tparam uint state
        {
            name = "set_tap",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set tap-to-click button map
        --
        -- Set the finger number to button number mapping for tap-to-click. The
        -- default mapping on most devices is to have a 1, 2 and 3 finger tap to
        -- map to the left, right and middle button, respectively.
        -- @function river_libinput_device_v1:set_tap_button_map
        -- @treturn river_libinput_result_v1
        -- @tparam uint button_map
        {
            name = "set_tap_button_map",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set tap-and-drag state
        --
        -- Configure tap-and-drag functionality on the device.
        -- @function river_libinput_device_v1:set_drag
        -- @treturn river_libinput_result_v1
        -- @tparam uint state
        {
            name = "set_drag",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set drag lock state
        --
        -- Configure drag-lock during tapping on this device. When enabled, a
        -- finger may be lifted and put back on the touchpad and the drag process
        -- continues. A timeout for lifting the finger is optional. When disabled,
        -- lifting the finger during a tap-and-drag will immediately stop the drag.
        -- See the libinput documentation for more details.
        -- @function river_libinput_device_v1:set_drag_lock
        -- @treturn river_libinput_result_v1
        -- @tparam uint state
        {
            name = "set_drag_lock",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set three finger drag state
        --
        -- Configure three finger drag functionality for the device.
        -- @function river_libinput_device_v1:set_three_finger_drag
        -- @treturn river_libinput_result_v1
        -- @tparam uint state
        {
            name = "set_three_finger_drag",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set calibration matrix
        --
        -- Set calibration matrix.
        -- @function river_libinput_device_v1:set_calibration_matrix
        -- @treturn river_libinput_result_v1
        -- @tparam array matrix array of 6 floats
        {
            name = "set_calibration_matrix",
            signature = "na",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set send events mode
        --
        -- Set the acceleration profile.
        -- @function river_libinput_device_v1:set_accel_profile
        -- @treturn river_libinput_result_v1
        -- @tparam uint profile
        {
            name = "set_accel_profile",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set acceleration speed
        --
        -- Set the acceleration speed within a range of [-1, 1], where 0 is
        -- the default acceleration for this device, -1 is the slowest acceleration
        -- and 1 is the maximum acceleration available on this device.
        -- @function river_libinput_device_v1:set_accel_speed
        -- @treturn river_libinput_result_v1
        -- @tparam array speed double
        {
            name = "set_accel_speed",
            signature = "na",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- apply acceleration config
        --
        -- Apply a pointer accleration config.
        -- @function river_libinput_device_v1:apply_accel_config
        -- @treturn river_libinput_result_v1
        -- @tparam river_libinput_accel_config_v1 config
        {
            name = "apply_accel_config",
            signature = "no",
            types = { wau.river_libinput_result_v1, wau.river_libinput_accel_config_v1, },
        },
        --- set natural scroll state
        --
        -- Set natural scroll state.
        -- @function river_libinput_device_v1:set_natural_scroll
        -- @treturn river_libinput_result_v1
        -- @tparam uint state
        {
            name = "set_natural_scroll",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set left-handed mode state
        --
        -- Set left-handed mode state.
        -- @function river_libinput_device_v1:set_left_handed
        -- @treturn river_libinput_result_v1
        -- @tparam uint state
        {
            name = "set_left_handed",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set click method
        --
        -- Set click method.
        -- @function river_libinput_device_v1:set_click_method
        -- @treturn river_libinput_result_v1
        -- @tparam uint method
        {
            name = "set_click_method",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set clickfinger button map
        --
        -- Set clickfinger button map.
        -- Supported if click_methods.clickfinger is supported.
        -- @function river_libinput_device_v1:set_clickfinger_button_map
        -- @treturn river_libinput_result_v1
        -- @tparam uint button_map
        {
            name = "set_clickfinger_button_map",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set middle mouse button emulation state
        --
        -- Set middle mouse button emulation state.
        -- @function river_libinput_device_v1:set_middle_emulation
        -- @treturn river_libinput_result_v1
        -- @tparam uint state
        {
            name = "set_middle_emulation",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set scroll method
        --
        -- Set scroll method.
        -- @function river_libinput_device_v1:set_scroll_method
        -- @treturn river_libinput_result_v1
        -- @tparam uint method
        {
            name = "set_scroll_method",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set scroll button
        --
        -- Set scroll button.
        -- Supported if scroll_methods.on_button_down is supported.
        -- @function river_libinput_device_v1:set_scroll_button
        -- @treturn river_libinput_result_v1
        -- @tparam uint button
        {
            name = "set_scroll_button",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set scroll button lock state
        --
        -- Set scroll button lock state.
        -- Supported if scroll_methods.on_button_down is supported.
        -- @function river_libinput_device_v1:set_scroll_button_lock
        -- @treturn river_libinput_result_v1
        -- @tparam uint state
        {
            name = "set_scroll_button_lock",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set disable-while-typing state
        --
        -- Set disable-while-typing state.
        -- @function river_libinput_device_v1:set_dwt
        -- @treturn river_libinput_result_v1
        -- @tparam uint state
        {
            name = "set_dwt",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set disable-while-trackpointing state
        --
        -- Set disable-while-trackpointing state.
        -- @function river_libinput_device_v1:set_dwtp
        -- @treturn river_libinput_result_v1
        -- @tparam uint state
        {
            name = "set_dwtp",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
        --- set rotation angle
        --
        -- Set rotation angle in degrees clockwise off the logical neutral
        -- position. Angle must be in the range [0-360).
        -- @function river_libinput_device_v1:set_rotation
        -- @treturn river_libinput_result_v1
        -- @tparam uint angle
        {
            name = "set_rotation",
            signature = "nu",
            types = { wau.river_libinput_result_v1, 0, },
        },
    },
    events = {
        --- the libinput device is removed
        --
        -- This event indicates that the libinput device has been removed.
        -- The server will send no further events on this object and ignore any
        -- request (other than river_libinput_device_v1.destroy) made after this
        -- event is sent. The client should destroy this object with the
        -- river_libinput_device_v1.destroy request to free up resources.
        -- @event river_libinput_device_v1:removed
        {
            name = "removed",
            signature = "",
            types = { },
        },
        --- corresponding river input device
        --
        -- The river_input_device_v1 corresponding to this libinput device.
        -- This event will always be the first event sent on the
        -- river_libinput_device_v1 object, and it will be sent exactly once.
        -- @event river_libinput_device_v1:input_device
        -- @tparam river_input_device_v1 device
        {
            name = "input_device",
            signature = "o",
            types = { wau.river_input_device_v1, },
        },
        --- supported send events modes
        --
        -- Supported send events modes.
        -- @event river_libinput_device_v1:send_events_support
        -- @tparam uint modes
        {
            name = "send_events_support",
            signature = "u",
            types = { 0, },
        },
        --- default send events mode
        --
        -- Default send events mode.
        -- @event river_libinput_device_v1:send_events_default
        -- @tparam uint mode
        {
            name = "send_events_default",
            signature = "u",
            types = { 0, },
        },
        --- current send events mode
        --
        -- Current send events mode.
        -- @event river_libinput_device_v1:send_events_current
        -- @tparam uint mode
        {
            name = "send_events_current",
            signature = "u",
            types = { 0, },
        },
        --- tap-to-click/drag support
        --
        -- The number of fingers supported for tap-to-click/drag.
        -- If finger_count is 0, tap-to-click and drag are unsupported.
        -- @event river_libinput_device_v1:tap_support
        -- @tparam int finger_count
        {
            name = "tap_support",
            signature = "i",
            types = { 0, },
        },
        --- default tap-to-click state
        --
        -- Default tap-to-click state.
        -- @event river_libinput_device_v1:tap_default
        -- @tparam uint state
        {
            name = "tap_default",
            signature = "u",
            types = { 0, },
        },
        --- current tap-to-click state
        --
        -- Current tap-to-click state.
        -- @event river_libinput_device_v1:tap_current
        -- @tparam uint state
        {
            name = "tap_current",
            signature = "u",
            types = { 0, },
        },
        --- default tap-to-click button map
        --
        -- Default tap-to-click button map.
        -- @event river_libinput_device_v1:tap_button_map_default
        -- @tparam uint button_map
        {
            name = "tap_button_map_default",
            signature = "u",
            types = { 0, },
        },
        --- current tap-to-click button map
        --
        -- Current tap-to-click button map.
        -- @event river_libinput_device_v1:tap_button_map_current
        -- @tparam uint button_map
        {
            name = "tap_button_map_current",
            signature = "u",
            types = { 0, },
        },
        --- default tap-and-drag state
        --
        -- Default tap-and-drag state.
        -- @event river_libinput_device_v1:drag_default
        -- @tparam uint state
        {
            name = "drag_default",
            signature = "u",
            types = { 0, },
        },
        --- current tap-and-drag state
        --
        -- Current tap-and-drag state.
        -- @event river_libinput_device_v1:drag_current
        -- @tparam uint state
        {
            name = "drag_current",
            signature = "u",
            types = { 0, },
        },
        --- default drag lock state
        --
        -- Default drag lock state.
        -- @event river_libinput_device_v1:drag_lock_default
        -- @tparam uint state
        {
            name = "drag_lock_default",
            signature = "u",
            types = { 0, },
        },
        --- current drag lock state
        --
        -- Current drag lock state.
        -- @event river_libinput_device_v1:drag_lock_current
        -- @tparam uint state
        {
            name = "drag_lock_current",
            signature = "u",
            types = { 0, },
        },
        --- three finger drag support
        --
        -- The number of fingers supported for three/four finger drag.
        -- If finger_count is less than 3, three finger drag is unsupported.
        -- @event river_libinput_device_v1:three_finger_drag_support
        -- @tparam int finger_count
        {
            name = "three_finger_drag_support",
            signature = "i",
            types = { 0, },
        },
        --- default three finger drag state
        --
        -- Default three finger drag state.
        -- @event river_libinput_device_v1:three_finger_drag_default
        -- @tparam uint state
        {
            name = "three_finger_drag_default",
            signature = "u",
            types = { 0, },
        },
        --- current three finger drag state
        --
        -- Current three finger drag state.
        -- @event river_libinput_device_v1:three_finger_drag_current
        -- @tparam uint state
        {
            name = "three_finger_drag_current",
            signature = "u",
            types = { 0, },
        },
        --- support for a calibration matrix
        --
        -- A calibration matrix is supported if the supported argument is non-zero.
        -- @event river_libinput_device_v1:calibration_matrix_support
        -- @tparam int supported boolean
        {
            name = "calibration_matrix_support",
            signature = "i",
            types = { 0, },
        },
        --- default calibration matrix
        --
        -- Default calibration matrix.
        -- @event river_libinput_device_v1:calibration_matrix_default
        -- @tparam array matrix array of 6 floats
        {
            name = "calibration_matrix_default",
            signature = "a",
            types = { 0, },
        },
        --- current calibration matrix
        --
        -- Current calibration matrix.
        -- @event river_libinput_device_v1:calibration_matrix_current
        -- @tparam array matrix array of 6 floats
        {
            name = "calibration_matrix_current",
            signature = "a",
            types = { 0, },
        },
        --- supported acceleration profiles
        --
        -- Supported acceleration profiles.
        -- @event river_libinput_device_v1:accel_profiles_support
        -- @tparam uint profiles
        {
            name = "accel_profiles_support",
            signature = "u",
            types = { 0, },
        },
        --- default acceleration profile
        --
        -- Default acceleration profile.
        -- @event river_libinput_device_v1:accel_profile_default
        -- @tparam uint profile
        {
            name = "accel_profile_default",
            signature = "u",
            types = { 0, },
        },
        --- current send events mode
        --
        -- Current acceleration profile.
        -- @event river_libinput_device_v1:accel_profile_current
        -- @tparam uint profile
        {
            name = "accel_profile_current",
            signature = "u",
            types = { 0, },
        },
        --- default acceleration speed
        --
        -- Default acceleration speed.
        -- @event river_libinput_device_v1:accel_speed_default
        -- @tparam array speed double
        {
            name = "accel_speed_default",
            signature = "a",
            types = { 0, },
        },
        --- current acceleration speed
        --
        -- Current acceleration speed.
        -- @event river_libinput_device_v1:accel_speed_current
        -- @tparam array speed double
        {
            name = "accel_speed_current",
            signature = "a",
            types = { 0, },
        },
        --- support for natural scroll
        --
        -- Natural scroll is supported if the supported argument is non-zero.
        -- @event river_libinput_device_v1:natural_scroll_support
        -- @tparam int supported boolean
        {
            name = "natural_scroll_support",
            signature = "i",
            types = { 0, },
        },
        --- default natural scroll
        --
        -- Default natural scroll.
        -- @event river_libinput_device_v1:natural_scroll_default
        -- @tparam uint state
        {
            name = "natural_scroll_default",
            signature = "u",
            types = { 0, },
        },
        --- current natural scroll state
        --
        -- Current natural scroll.
        -- @event river_libinput_device_v1:natural_scroll_current
        -- @tparam uint state
        {
            name = "natural_scroll_current",
            signature = "u",
            types = { 0, },
        },
        --- support for left-handed mode
        --
        -- Left-handed mode is supported if the supported argument is non-zero.
        -- @event river_libinput_device_v1:left_handed_support
        -- @tparam int supported boolean
        {
            name = "left_handed_support",
            signature = "i",
            types = { 0, },
        },
        --- default left-handed mode
        --
        -- Default left-handed mode.
        -- @event river_libinput_device_v1:left_handed_default
        -- @tparam uint state
        {
            name = "left_handed_default",
            signature = "u",
            types = { 0, },
        },
        --- current left-handed mode state
        --
        -- Current left-handed mode.
        -- @event river_libinput_device_v1:left_handed_current
        -- @tparam uint state
        {
            name = "left_handed_current",
            signature = "u",
            types = { 0, },
        },
        --- supported click methods
        --
        -- The click methods supported by the device.
        -- @event river_libinput_device_v1:click_method_support
        -- @tparam uint methods
        {
            name = "click_method_support",
            signature = "u",
            types = { 0, },
        },
        --- default click method
        --
        -- Default click method.
        -- @event river_libinput_device_v1:click_method_default
        -- @tparam uint method
        {
            name = "click_method_default",
            signature = "u",
            types = { 0, },
        },
        --- current click method
        --
        -- Current click method.
        -- @event river_libinput_device_v1:click_method_current
        -- @tparam uint method
        {
            name = "click_method_current",
            signature = "u",
            types = { 0, },
        },
        --- default clickfinger button map
        --
        -- Default clickfinger button map.
        -- Supported if click_methods.clickfinger is supported.
        -- @event river_libinput_device_v1:clickfinger_button_map_default
        -- @tparam uint button_map
        {
            name = "clickfinger_button_map_default",
            signature = "u",
            types = { 0, },
        },
        --- current clickfinger button map
        --
        -- Current clickfinger button map.
        -- Supported if click_methods.clickfinger is supported.
        -- @event river_libinput_device_v1:clickfinger_button_map_current
        -- @tparam uint button_map
        {
            name = "clickfinger_button_map_current",
            signature = "u",
            types = { 0, },
        },
        --- support for middle mouse button emulation
        --
        -- Middle mouse button emulation is supported if the supported argument is
        -- non-zero.
        -- @event river_libinput_device_v1:middle_emulation_support
        -- @tparam int supported boolean
        {
            name = "middle_emulation_support",
            signature = "i",
            types = { 0, },
        },
        --- default middle mouse button emulation
        --
        -- Default middle mouse button emulation.
        -- @event river_libinput_device_v1:middle_emulation_default
        -- @tparam uint state
        {
            name = "middle_emulation_default",
            signature = "u",
            types = { 0, },
        },
        --- current middle mouse button emulation state
        --
        -- Current middle mouse button emulation.
        -- @event river_libinput_device_v1:middle_emulation_current
        -- @tparam uint state
        {
            name = "middle_emulation_current",
            signature = "u",
            types = { 0, },
        },
        --- supported scroll methods
        --
        -- The scroll methods supported by the device.
        -- @event river_libinput_device_v1:scroll_method_support
        -- @tparam uint methods
        {
            name = "scroll_method_support",
            signature = "u",
            types = { 0, },
        },
        --- default scroll method
        --
        -- Default scroll method.
        -- @event river_libinput_device_v1:scroll_method_default
        -- @tparam uint method
        {
            name = "scroll_method_default",
            signature = "u",
            types = { 0, },
        },
        --- current scroll method
        --
        -- Current scroll method.
        -- @event river_libinput_device_v1:scroll_method_current
        -- @tparam uint method
        {
            name = "scroll_method_current",
            signature = "u",
            types = { 0, },
        },
        --- default scroll button
        --
        -- Default scroll button.
        -- Supported if scroll_methods.on_button_down is supported.
        -- @event river_libinput_device_v1:scroll_button_default
        -- @tparam uint button
        {
            name = "scroll_button_default",
            signature = "u",
            types = { 0, },
        },
        --- current scroll button
        --
        -- Current scroll button.
        -- Supported if scroll_methods.on_button_down is supported.
        -- @event river_libinput_device_v1:scroll_button_current
        -- @tparam uint button
        {
            name = "scroll_button_current",
            signature = "u",
            types = { 0, },
        },
        --- default scroll button lock state
        --
        -- Default scroll button lock state.
        -- Supported if scroll_methods.on_button_down is supported.
        -- @event river_libinput_device_v1:scroll_button_lock_default
        -- @tparam uint state
        {
            name = "scroll_button_lock_default",
            signature = "u",
            types = { 0, },
        },
        --- current scroll button lock state
        --
        -- Current scroll button lock state.
        -- Supported if scroll_methods.on_button_down is supported.
        -- @event river_libinput_device_v1:scroll_button_lock_current
        -- @tparam uint state
        {
            name = "scroll_button_lock_current",
            signature = "u",
            types = { 0, },
        },
        --- support for disable-while-typing
        --
        -- Disable-while-typing is supported if the supported argument is
        -- non-zero.
        -- @event river_libinput_device_v1:dwt_support
        -- @tparam int supported boolean
        {
            name = "dwt_support",
            signature = "i",
            types = { 0, },
        },
        --- default disable-while-typing state
        --
        -- Default disable-while-typing state.
        -- @event river_libinput_device_v1:dwt_default
        -- @tparam uint state
        {
            name = "dwt_default",
            signature = "u",
            types = { 0, },
        },
        --- current disable-while-typing state
        --
        -- Current disable-while-typing state.
        -- @event river_libinput_device_v1:dwt_current
        -- @tparam uint state
        {
            name = "dwt_current",
            signature = "u",
            types = { 0, },
        },
        --- support for disable-while-trackpointing
        --
        -- Disable-while-trackpointing is supported if the supported argument is
        -- non-zero.
        -- @event river_libinput_device_v1:dwtp_support
        -- @tparam int supported boolean
        {
            name = "dwtp_support",
            signature = "i",
            types = { 0, },
        },
        --- default disable-while-trackpointing state
        --
        -- Default disable-while-trackpointing state.
        -- @event river_libinput_device_v1:dwtp_default
        -- @tparam uint state
        {
            name = "dwtp_default",
            signature = "u",
            types = { 0, },
        },
        --- current disable-while-trackpointing state
        --
        -- Current disable-while-trackpointing state.
        -- @event river_libinput_device_v1:dwtp_current
        -- @tparam uint state
        {
            name = "dwtp_current",
            signature = "u",
            types = { 0, },
        },
        --- support for rotation
        --
        -- Rotation is supported if the supported argument is non-zero.
        -- @event river_libinput_device_v1:rotation_support
        -- @tparam int supported boolean
        {
            name = "rotation_support",
            signature = "i",
            types = { 0, },
        },
        --- default rotation angle
        --
        -- Default rotation angle.
        -- @event river_libinput_device_v1:rotation_default
        -- @tparam uint angle
        {
            name = "rotation_default",
            signature = "u",
            types = { 0, },
        },
        --- current rotation angle
        --
        -- Current rotation angle.
        -- @event river_libinput_device_v1:rotation_current
        -- @tparam uint angle
        {
            name = "rotation_current",
            signature = "u",
            types = { 0, },
        },
    },
    enums = {
        --- error
        -- @enum river_libinput_device_v1.Error
        -- @param INVALID_ARG 0 invalid enum value or similar
        ["error"] = {
            ["invalid_arg"] = 0,
        },
        --- send_events_modes
        -- @enum river_libinput_device_v1.SendEventsModes
        -- @param ENABLED 0
        -- @param DISABLED 1
        -- @param DISABLED_ON_EXTERNAL_MOUSE 2
        ["send_events_modes"] = {
            ["enabled"] = 0,
            ["disabled"] = 1,
            ["disabled_on_external_mouse"] = 2,
        },
        --- tap_state
        -- @enum river_libinput_device_v1.TapState
        -- @param DISABLED 0
        -- @param ENABLED 1
        ["tap_state"] = {
            ["disabled"] = 0,
            ["enabled"] = 1,
        },
        --- tap_button_map
        -- @enum river_libinput_device_v1.TapButtonMap
        -- @param LRM 0 1/2/3 finger tap maps to left/right/middle
        -- @param LMR 1 1/2/3 finger tap maps to left/middle/right
        ["tap_button_map"] = {
            ["lrm"] = 0,
            ["lmr"] = 1,
        },
        --- drag_state
        -- @enum river_libinput_device_v1.DragState
        -- @param DISABLED 0
        -- @param ENABLED 1
        ["drag_state"] = {
            ["disabled"] = 0,
            ["enabled"] = 1,
        },
        --- drag_lock_state
        -- @enum river_libinput_device_v1.DragLockState
        -- @param DISABLED 0
        -- @param ENABLED_TIMEOUT 1
        -- @param ENABLED_STICKY 2
        ["drag_lock_state"] = {
            ["disabled"] = 0,
            ["enabled_timeout"] = 1,
            ["enabled_sticky"] = 2,
        },
        --- three_finger_drag_state
        -- @enum river_libinput_device_v1.ThreeFingerDragState
        -- @param DISABLED 0
        -- @param ENABLED_3FG 1
        -- @param ENABLED_4FG 2
        ["three_finger_drag_state"] = {
            ["disabled"] = 0,
            ["enabled_3fg"] = 1,
            ["enabled_4fg"] = 2,
        },
        --- accel_profile
        -- @enum river_libinput_device_v1.AccelProfile
        -- @param NONE 0
        -- @param FLAT 1
        -- @param ADAPTIVE 2
        -- @param CUSTOM 4
        ["accel_profile"] = {
            ["none"] = 0,
            ["flat"] = 1,
            ["adaptive"] = 2,
            ["custom"] = 4,
        },
        --- accel_profiles
        -- @enum river_libinput_device_v1.AccelProfiles
        -- @param NONE 0
        -- @param FLAT 1
        -- @param ADAPTIVE 2
        -- @param CUSTOM 4
        ["accel_profiles"] = {
            ["none"] = 0,
            ["flat"] = 1,
            ["adaptive"] = 2,
            ["custom"] = 4,
        },
        --- natural_scroll_state
        -- @enum river_libinput_device_v1.NaturalScrollState
        -- @param DISABLED 0
        -- @param ENABLED 1
        ["natural_scroll_state"] = {
            ["disabled"] = 0,
            ["enabled"] = 1,
        },
        --- left_handed_state
        -- @enum river_libinput_device_v1.LeftHandedState
        -- @param DISABLED 0
        -- @param ENABLED 1
        ["left_handed_state"] = {
            ["disabled"] = 0,
            ["enabled"] = 1,
        },
        --- click_method
        -- @enum river_libinput_device_v1.ClickMethod
        -- @param NONE 0
        -- @param BUTTON_AREAS 1
        -- @param CLICKFINGER 2
        ["click_method"] = {
            ["none"] = 0,
            ["button_areas"] = 1,
            ["clickfinger"] = 2,
        },
        --- click_methods
        -- @enum river_libinput_device_v1.ClickMethods
        -- @param NONE 0
        -- @param BUTTON_AREAS 1
        -- @param CLICKFINGER 2
        ["click_methods"] = {
            ["none"] = 0,
            ["button_areas"] = 1,
            ["clickfinger"] = 2,
        },
        --- clickfinger_button_map
        -- @enum river_libinput_device_v1.ClickfingerButtonMap
        -- @param LRM 0
        -- @param LMR 1
        ["clickfinger_button_map"] = {
            ["lrm"] = 0,
            ["lmr"] = 1,
        },
        --- middle_emulation_state
        -- @enum river_libinput_device_v1.MiddleEmulationState
        -- @param DISABLED 0
        -- @param ENABLED 1
        ["middle_emulation_state"] = {
            ["disabled"] = 0,
            ["enabled"] = 1,
        },
        --- scroll_method
        -- @enum river_libinput_device_v1.ScrollMethod
        -- @param NO_SCROLL 0
        -- @param TWO_FINGER 1
        -- @param EDGE 2
        -- @param ON_BUTTON_DOWN 4
        ["scroll_method"] = {
            ["no_scroll"] = 0,
            ["two_finger"] = 1,
            ["edge"] = 2,
            ["on_button_down"] = 4,
        },
        --- scroll_methods
        -- @enum river_libinput_device_v1.ScrollMethods
        -- @param NO_SCROLL 0
        -- @param TWO_FINGER 1
        -- @param EDGE 2
        -- @param ON_BUTTON_DOWN 4
        ["scroll_methods"] = {
            ["no_scroll"] = 0,
            ["two_finger"] = 1,
            ["edge"] = 2,
            ["on_button_down"] = 4,
        },
        --- scroll_button_lock_state
        -- @enum river_libinput_device_v1.ScrollButtonLockState
        -- @param DISABLED 0
        -- @param ENABLED 1
        ["scroll_button_lock_state"] = {
            ["disabled"] = 0,
            ["enabled"] = 1,
        },
        --- dwt_state
        -- @enum river_libinput_device_v1.DwtState
        -- @param DISABLED 0
        -- @param ENABLED 1
        ["dwt_state"] = {
            ["disabled"] = 0,
            ["enabled"] = 1,
        },
        --- dwtp_state
        -- @enum river_libinput_device_v1.DwtpState
        -- @param DISABLED 0
        -- @param ENABLED 1
        ["dwtp_state"] = {
            ["disabled"] = 0,
            ["enabled"] = 1,
        },
    },
    methods_opcode = {
        ["destroy"] = 0,
        ["set_send_events"] = 1,
        ["set_tap"] = 2,
        ["set_tap_button_map"] = 3,
        ["set_drag"] = 4,
        ["set_drag_lock"] = 5,
        ["set_three_finger_drag"] = 6,
        ["set_calibration_matrix"] = 7,
        ["set_accel_profile"] = 8,
        ["set_accel_speed"] = 9,
        ["apply_accel_config"] = 10,
        ["set_natural_scroll"] = 11,
        ["set_left_handed"] = 12,
        ["set_click_method"] = 13,
        ["set_clickfinger_button_map"] = 14,
        ["set_middle_emulation"] = 15,
        ["set_scroll_method"] = 16,
        ["set_scroll_button"] = 17,
        ["set_scroll_button_lock"] = 18,
        ["set_dwt"] = 19,
        ["set_dwtp"] = 20,
        ["set_rotation"] = 21,
    },
}

--- acceleration config
--
-- The result returned by libinput on setting configuration for a device.
-- @type river_libinput_accel_config_v1
wau.river_libinput_accel_config_v1:init {
    name = "river_libinput_accel_config_v1",
    version = 1,
    methods = {
        --- destroy the accel object
        --
        -- This request indicates that the client will no longer use the accel
        -- config object and that it may be safely destroyed.
        -- @function river_libinput_accel_config_v1:destroy
        -- @treturn river_libinput_accel_config_v1 self
        {
            name = "destroy",
            signature = "",
            types = { },
            type = "destructor"
        },
        --- define custom acceleration function
        --
        -- Defines the acceleration function for a given movement type
        -- in an acceleration configuration with custom accel profile.
        -- @function river_libinput_accel_config_v1:set_points
        -- @treturn river_libinput_result_v1
        -- @tparam uint type
        -- @tparam array step double
        -- @tparam array points array of doubles
        {
            name = "set_points",
            signature = "nuaa",
            types = { wau.river_libinput_result_v1, 0, 0, 0, },
        },
    },
    events = {
    },
    enums = {
        --- error
        -- @enum river_libinput_accel_config_v1.Error
        -- @param INVALID_ARG 0 invalid enum value or similar
        ["error"] = {
            ["invalid_arg"] = 0,
        },
        --- accel_type
        -- @enum river_libinput_accel_config_v1.AccelType
        -- @param FALLBACK 0
        -- @param MOTION 1
        -- @param SCROLL 2
        ["accel_type"] = {
            ["fallback"] = 0,
            ["motion"] = 1,
            ["scroll"] = 2,
        },
    },
    methods_opcode = {
        ["destroy"] = 0,
        ["set_points"] = 1,
    },
}

--- config application result
--
-- The result returned by libinput on setting configuration for a device.
-- @type river_libinput_result_v1
wau.river_libinput_result_v1:init {
    name = "river_libinput_result_v1",
    version = 1,
    methods = {
    },
    events = {
        --- config success
        --
        -- The configuration was successfully applied to the device.
        -- @event river_libinput_result_v1:success
        {
            name = "success",
            signature = "",
            types = { },
            type = "destructor"
        },
        --- config unsupported
        --
        -- The configuration is unsupported by the device and was ignored.
        -- @event river_libinput_result_v1:unsupported
        {
            name = "unsupported",
            signature = "",
            types = { },
            type = "destructor"
        },
        --- config invalid
        --
        -- The configuration is invalid and was ignored.
        -- @event river_libinput_result_v1:invalid
        {
            name = "invalid",
            signature = "",
            types = { },
            type = "destructor"
        },
    },
    enums = {
    },
    methods_opcode = {
    },
}

end
