-- Auto generated by the wau-scanner v0

--- river_layer_shell_v1
-- @module river_layer_shell_v1

-- SPDX-FileCopyrightText: © 2025 Isaac Freund
-- SPDX-License-Identifier: MIT
-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to
-- deal in the Software without restriction, including without limitation the
-- rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
-- sell copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:
-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
-- FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
-- IN THE SOFTWARE.
return function(wau)

local interfaces = {
    "river_layer_shell_v1",
    "river_layer_shell_output_v1",
    "river_layer_shell_seat_v1",
}

for _, iface in ipairs(interfaces) do
    wau[iface] = wau.wl_interface.new()
end

--- river layer shell global interface
--
-- This global interface should only be advertised to the client if the
-- river_window_manager_v1 global is also advertised. Binding this interface
-- indicates that the window manager supports layer shell.
-- If the window manager does not bind this interface, the compositor should
-- not allow clients to map layer surfaces. This can be achieved by
-- closing layer surfaces immediately.
-- @type river_layer_shell_v1
wau.river_layer_shell_v1:init {
    name = "river_layer_shell_v1",
    version = 1,
    methods = {
        --- destroy the river_layer_shell_v1 object
        --
        -- This request indicates that the client will no longer use the
        -- river_layer_shell_v1 object.
        -- @function river_layer_shell_v1:destroy
        -- @treturn river_layer_shell_v1 self
        {
            name = "destroy",
            signature = "",
            types = { },
            type = "destructor"
        },
        --- get layer shell output state
        --
        -- It is a protocol error to make this request more than once for a given
        -- river_output_v1 object.
        -- @function river_layer_shell_v1:get_output
        -- @treturn river_layer_shell_output_v1
        -- @tparam river_output_v1 output
        {
            name = "get_output",
            signature = "no",
            types = { wau.river_layer_shell_output_v1, wau.river_output_v1, },
        },
        --- get layer shell seat state
        --
        -- It is a protocol error to make this request more than once for a given
        -- river_seat_v1 object.
        -- @function river_layer_shell_v1:get_seat
        -- @treturn river_layer_shell_seat_v1
        -- @tparam river_seat_v1 seat
        {
            name = "get_seat",
            signature = "no",
            types = { wau.river_layer_shell_seat_v1, wau.river_seat_v1, },
        },
    },
    events = {
    },
    enums = {
        --- error
        -- @enum river_layer_shell_v1.Error
        -- @param OBJECT_ALREADY_CREATED 0 the layer_shell_output/seat object was already created.
        ["error"] = {
            ["object_already_created"] = 0,
        },
    },
    methods_opcode = {
        ["destroy"] = 0,
        ["get_output"] = 1,
        ["get_seat"] = 2,
    },
}

--- layer shell output state
--
-- The lifetime of this object is tied to the corresponding river_output_v1.
-- This object is made inert when the river_output_v1.removed event is sent
-- and should be destroyed.
-- @type river_layer_shell_output_v1
wau.river_layer_shell_output_v1:init {
    name = "river_layer_shell_output_v1",
    version = 1,
    methods = {
        --- destroy the object
        --
        -- This request indicates that the client will no longer use the
        -- river_layer_shell_output_v1 object and that it may be safely destroyed.
        -- This request should be made after the river_output_v1.removed event is
        -- received to complete destruction of the output.
        -- @function river_layer_shell_output_v1:destroy
        -- @treturn river_layer_shell_output_v1 self
        {
            name = "destroy",
            signature = "",
            types = { },
            type = "destructor"
        },
        --- Set default output for layer surfaces
        --
        -- Mark this output as the default for new layer surfaces which do not
        -- request a specific output themselves. This request overrides any
        -- previous set_default request on any river_layer_shell_output_v1 object.
        -- If no set_default request is made or if the default output is destroyed,
        -- the default output is undefined until the next set_default request.
        -- This request modifies window management state and may only be made as
        -- part of a manage sequence, see the river_window_manager_v1 description.
        -- @function river_layer_shell_output_v1:set_default
        -- @treturn river_layer_shell_output_v1 self
        {
            name = "set_default",
            signature = "",
            types = { },
        },
    },
    events = {
        --- area left after subtracting exclusive zones
        --
        -- This event indicates the area of the output remaining after subtracting
        -- the exclusive zones of layer surfaces. Exclusive zones are a hint, the
        -- window manager is free to ignore this area hint if it wishes.
        -- The x and y values are in the global coordinate space, not relative to
        -- the position of the output.
        -- This event will be followed by a manage_start event after all other new
        -- state has been sent by the server.
        -- @event river_layer_shell_output_v1:non_exclusive_area
        -- @tparam int x global x coordinate
        -- @tparam int y global y coordinate
        -- @tparam int width area width
        -- @tparam int height area height
        {
            name = "non_exclusive_area",
            signature = "iiii",
            types = { 0, 0, 0, 0, },
        },
    },
    enums = {
    },
    methods_opcode = {
        ["destroy"] = 0,
        ["set_default"] = 1,
    },
}

--- layer shell seat state
--
-- The lifetime of this object is tied to the corresponding river_seat_v1.
-- This object is made inert when the river_seat_v1.removed event is sent and
-- should be destroyed.
-- @type river_layer_shell_seat_v1
wau.river_layer_shell_seat_v1:init {
    name = "river_layer_shell_seat_v1",
    version = 1,
    methods = {
        --- destroy the object
        --
        -- This request indicates that the client will no longer use the
        -- river_layer_shell_seat_v1 object and that it may be safely destroyed.
        -- This request should be made after the river_seat_v1.removed event is
        -- received to complete destruction of the seat.
        -- @function river_layer_shell_seat_v1:destroy
        -- @treturn river_layer_shell_seat_v1 self
        {
            name = "destroy",
            signature = "",
            types = { },
            type = "destructor"
        },
    },
    events = {
        --- layer shell surface has exclusive focus
        --
        -- A layer shell surface will be given exclusive keyboard focus at the end
        -- of the manage sequence in which this event is sent. The window manager
        -- may want to update window decorations or similar to indicate that no
        -- window is focused.
        -- Until the focus_non_exclusive or focus_none event is sent, all window
        -- manager requests to change focus are ignored.
        -- This event will be followed by a manage_start event after all other new
        -- state has been sent by the server.
        -- @event river_layer_shell_seat_v1:focus_exclusive
        {
            name = "focus_exclusive",
            signature = "",
            types = { },
        },
        --- layer shell surface wants non-exclusive focus
        --
        -- A layer shell surface will be given non-exclusive keyboard focus at the
        -- end of the manage sequence in which this event is sent. The window
        -- manager may want to update window decorations or similar to indicate
        -- that no window is focused.
        -- The window manager continues to control focus and may choose to focus a
        -- different window/shell surface at any time. If the window manager sets
        -- focus during the same manage sequence in which this event is sent, the
        -- layer surface will not be focused.
        -- If the layer surface with non-exclusive focus is closed or the window
        -- manager chooses to move focus away from the layer surface, a focus_none
        -- event will be sent in the next manage sequence.
        -- This event will be followed by a manage_start event after all other new
        -- state has been sent by the server.
        -- @event river_layer_shell_seat_v1:focus_non_exclusive
        {
            name = "focus_non_exclusive",
            signature = "",
            types = { },
        },
        --- no layer shell surface has focus
        --
        -- No layer shell surface will have keyboard focus at the end of the manage
        -- sequence in which this event is sent. The window manager may want to
        -- return focus to whichever window last had focus, for example.
        -- This event will be followed by a manage_start event after all other new
        -- state has been sent by the server.
        -- @event river_layer_shell_seat_v1:focus_none
        {
            name = "focus_none",
            signature = "",
            types = { },
        },
    },
    enums = {
    },
    methods_opcode = {
        ["destroy"] = 0,
    },
}

end
