-- Auto generated by the wau-scanner v0

--- wlr_output_management_unstable_v1
-- @module wlr_output_management_unstable_v1

-- Copyright © 2019 Purism SPC
-- Permission to use, copy, modify, distribute, and sell this
-- software and its documentation for any purpose is hereby granted
-- without fee, provided that the above copyright notice appear in
-- all copies and that both that copyright notice and this permission
-- notice appear in supporting documentation, and that the name of
-- the copyright holders not be used in advertising or publicity
-- pertaining to distribution of the software without specific,
-- written prior permission.  The copyright holders make no
-- representations about the suitability of this software for any
-- purpose.  It is provided "as is" without express or implied
-- warranty.
-- THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
-- SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
-- FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
-- SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
-- WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
-- AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
-- ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
-- THIS SOFTWARE.
return function(wau)

local interfaces = {
    "zwlr_output_manager_v1",
    "zwlr_output_head_v1",
    "zwlr_output_mode_v1",
    "zwlr_output_configuration_v1",
    "zwlr_output_configuration_head_v1",
}

for _, iface in ipairs(interfaces) do
    wau[iface] = wau.wl_interface.new()
end

--- output device configuration manager
--
-- This interface is a manager that allows reading and writing the current
-- output device configuration.
-- Output devices that display pixels (e.g. a physical monitor or a virtual
-- output in a window) are represented as heads. Heads cannot be created nor
-- destroyed by the client, but they can be enabled or disabled and their
-- properties can be changed. Each head may have one or more available modes.
-- Whenever a head appears (e.g. a monitor is plugged in), it will be
-- advertised via the head event. Immediately after the output manager is
-- bound, all current heads are advertised.
-- Whenever a head's properties change, the relevant wlr_output_head events
-- will be sent. Not all head properties will be sent: only properties that
-- have changed need to.
-- Whenever a head disappears (e.g. a monitor is unplugged), a
-- wlr_output_head.finished event will be sent.
-- After one or more heads appear, change or disappear, the done event will
-- be sent. It carries a serial which can be used in a create_configuration
-- request to update heads properties.
-- The information obtained from this protocol should only be used for output
-- configuration purposes. This protocol is not designed to be a generic
-- output property advertisement protocol for regular clients. Instead,
-- protocols such as xdg-output should be used.
-- @type zwlr_output_manager_v1
wau.zwlr_output_manager_v1:init {
    name = "zwlr_output_manager_v1",
    version = 4,
    methods = {
        --- create a new output configuration object
        --
        -- Create a new output configuration object. This allows to update head
        -- properties.
        -- @function zwlr_output_manager_v1:create_configuration
        -- @treturn zwlr_output_configuration_v1
        -- @tparam uint serial
        {
            name = "create_configuration",
            signature = "nu",
            types = { wau.zwlr_output_configuration_v1, 0, },
        },
        --- stop sending events
        --
        -- Indicates the client no longer wishes to receive events for output
        -- configuration changes. However the compositor may emit further events,
        -- until the finished event is emitted.
        -- The client must not send any more requests after this one.
        -- @function zwlr_output_manager_v1:stop
        -- @treturn zwlr_output_manager_v1 self
        {
            name = "stop",
            signature = "",
            types = { },
        },
    },
    events = {
        --- introduce a new head
        --
        -- This event introduces a new head. This happens whenever a new head
        -- appears (e.g. a monitor is plugged in) or after the output manager is
        -- bound.
        -- @event zwlr_output_manager_v1:head
        -- @tparam zwlr_output_head_v1 head
        {
            name = "head",
            signature = "n",
            types = { wau.zwlr_output_head_v1, },
        },
        --- sent all information about current configuration
        --
        -- This event is sent after all information has been sent after binding to
        -- the output manager object and after any subsequent changes. This applies
        -- to child head and mode objects as well. In other words, this event is
        -- sent whenever a head or mode is created or destroyed and whenever one of
        -- their properties has been changed. Not all state is re-sent each time
        -- the current configuration changes: only the actual changes are sent.
        -- This allows changes to the output configuration to be seen as atomic,
        -- even if they happen via multiple events.
        -- A serial is sent to be used in a future create_configuration request.
        -- @event zwlr_output_manager_v1:done
        -- @tparam uint serial current configuration serial
        {
            name = "done",
            signature = "u",
            types = { 0, },
        },
        --- the compositor has finished with the manager
        --
        -- This event indicates that the compositor is done sending manager events.
        -- The compositor will destroy the object immediately after sending this
        -- event, so it will become invalid and the client should release any
        -- resources associated with it.
        -- @event zwlr_output_manager_v1:finished
        {
            name = "finished",
            signature = "",
            types = { },
            type = "destructor"
        },
    },
    enums = {
    },
    methods_opcode = {
        ["create_configuration"] = 0,
        ["stop"] = 1,
    },
}

--- output device
--
-- A head is an output device. The difference between a wl_output object and
-- a head is that heads are advertised even if they are turned off. A head
-- object only advertises properties and cannot be used directly to change
-- them.
-- A head has some read-only properties: modes, name, description and
-- physical_size. These cannot be changed by clients.
-- Other properties can be updated via a wlr_output_configuration object.
-- Properties sent via this interface are applied atomically via the
-- wlr_output_manager.done event. No guarantees are made regarding the order
-- in which properties are sent.
-- @type zwlr_output_head_v1
wau.zwlr_output_head_v1:init {
    name = "zwlr_output_head_v1",
    version = 4,
    methods = {
        --- destroy the head object
        --
        -- This request indicates that the client will no longer use this head
        -- object.
        -- @function zwlr_output_head_v1:release
        -- @treturn zwlr_output_head_v1 self
        {
            name = "release",
            signature = "3",
            types = { },
            type = "destructor"
        },
    },
    events = {
        --- head name
        --
        -- This event describes the head name.
        -- The naming convention is compositor defined, but limited to alphanumeric
        -- characters and dashes (-). Each name is unique among all wlr_output_head
        -- objects, but if a wlr_output_head object is destroyed the same name may
        -- be reused later. The names will also remain consistent across sessions
        -- with the same hardware and software configuration.
        -- Examples of names include 'HDMI-A-1', 'WL-1', 'X11-1', etc. However, do
        -- not assume that the name is a reflection of an underlying DRM
        -- connector, X11 connection, etc.
        -- If this head matches a wl_output, the wl_output.name event must report
        -- the same name.
        -- The name event is sent after a wlr_output_head object is created. This
        -- event is only sent once per object, and the name does not change over
        -- the lifetime of the wlr_output_head object.
        -- @event zwlr_output_head_v1:name
        -- @tparam string name
        {
            name = "name",
            signature = "s",
            types = { 0, },
        },
        --- head description
        --
        -- This event describes a human-readable description of the head.
        -- The description is a UTF-8 string with no convention defined for its
        -- contents. Examples might include 'Foocorp 11" Display' or 'Virtual X11
        -- output via :1'. However, do not assume that the name is a reflection of
        -- the make, model, serial of the underlying DRM connector or the display
        -- name of the underlying X11 connection, etc.
        -- If this head matches a wl_output, the wl_output.description event must
        -- report the same name.
        -- The description event is sent after a wlr_output_head object is created.
        -- This event is only sent once per object, and the description does not
        -- change over the lifetime of the wlr_output_head object.
        -- @event zwlr_output_head_v1:description
        -- @tparam string description
        {
            name = "description",
            signature = "s",
            types = { 0, },
        },
        --- head physical size
        --
        -- This event describes the physical size of the head. This event is only
        -- sent if the head has a physical size (e.g. is not a projector or a
        -- virtual device).
        -- The physical size event is sent after a wlr_output_head object is created. This
        -- event is only sent once per object, and the physical size does not change over
        -- the lifetime of the wlr_output_head object.
        -- @event zwlr_output_head_v1:physical_size
        -- @tparam int width width in millimeters of the output
        -- @tparam int height height in millimeters of the output
        {
            name = "physical_size",
            signature = "ii",
            types = { 0, 0, },
        },
        --- introduce a mode
        --
        -- This event introduces a mode for this head. It is sent once per
        -- supported mode.
        -- @event zwlr_output_head_v1:mode
        -- @tparam zwlr_output_mode_v1 mode
        {
            name = "mode",
            signature = "n",
            types = { wau.zwlr_output_mode_v1, },
        },
        --- head is enabled or disabled
        --
        -- This event describes whether the head is enabled. A disabled head is not
        -- mapped to a region of the global compositor space.
        -- When a head is disabled, some properties (current_mode, position,
        -- transform and scale) are irrelevant.
        -- @event zwlr_output_head_v1:enabled
        -- @tparam int enabled zero if disabled, non-zero if enabled
        {
            name = "enabled",
            signature = "i",
            types = { 0, },
        },
        --- current mode
        --
        -- This event describes the mode currently in use for this head. It is only
        -- sent if the output is enabled.
        -- @event zwlr_output_head_v1:current_mode
        -- @tparam zwlr_output_mode_v1 mode
        {
            name = "current_mode",
            signature = "o",
            types = { wau.zwlr_output_mode_v1, },
        },
        --- current position
        --
        -- This events describes the position of the head in the global compositor
        -- space. It is only sent if the output is enabled.
        -- @event zwlr_output_head_v1:position
        -- @tparam int x x position within the global compositor space
        -- @tparam int y y position within the global compositor space
        {
            name = "position",
            signature = "ii",
            types = { 0, 0, },
        },
        --- current transformation
        --
        -- This event describes the transformation currently applied to the head.
        -- It is only sent if the output is enabled.
        -- @event zwlr_output_head_v1:transform
        -- @tparam int transform
        {
            name = "transform",
            signature = "i",
            types = { 0, },
        },
        --- current scale
        --
        -- This events describes the scale of the head in the global compositor
        -- space. It is only sent if the output is enabled.
        -- @event zwlr_output_head_v1:scale
        -- @tparam fixed scale
        {
            name = "scale",
            signature = "f",
            types = { 0, },
        },
        --- the head has disappeared
        --
        -- This event indicates that the head is no longer available. The head
        -- object becomes inert. Clients should send a destroy request and release
        -- any resources associated with it.
        -- @event zwlr_output_head_v1:finished
        {
            name = "finished",
            signature = "",
            types = { },
        },
        --- head manufacturer
        --
        -- This event describes the manufacturer of the head.
        -- Together with the model and serial_number events the purpose is to
        -- allow clients to recognize heads from previous sessions and for example
        -- load head-specific configurations back.
        -- It is not guaranteed this event will be ever sent. A reason for that
        -- can be that the compositor does not have information about the make of
        -- the head or the definition of a make is not sensible in the current
        -- setup, for example in a virtual session. Clients can still try to
        -- identify the head by available information from other events but should
        -- be aware that there is an increased risk of false positives.
        -- If sent, the make event is sent after a wlr_output_head object is
        -- created and only sent once per object. The make does not change over
        -- the lifetime of the wlr_output_head object.
        -- It is not recommended to display the make string in UI to users. For
        -- that the string provided by the description event should be preferred.
        -- @event zwlr_output_head_v1:make
        -- @tparam string make
        {
            name = "make",
            signature = "2s",
            types = { 0, },
        },
        --- head model
        --
        -- This event describes the model of the head.
        -- Together with the make and serial_number events the purpose is to
        -- allow clients to recognize heads from previous sessions and for example
        -- load head-specific configurations back.
        -- It is not guaranteed this event will be ever sent. A reason for that
        -- can be that the compositor does not have information about the model of
        -- the head or the definition of a model is not sensible in the current
        -- setup, for example in a virtual session. Clients can still try to
        -- identify the head by available information from other events but should
        -- be aware that there is an increased risk of false positives.
        -- If sent, the model event is sent after a wlr_output_head object is
        -- created and only sent once per object. The model does not change over
        -- the lifetime of the wlr_output_head object.
        -- It is not recommended to display the model string in UI to users. For
        -- that the string provided by the description event should be preferred.
        -- @event zwlr_output_head_v1:model
        -- @tparam string model
        {
            name = "model",
            signature = "2s",
            types = { 0, },
        },
        --- head serial number
        --
        -- This event describes the serial number of the head.
        -- Together with the make and model events the purpose is to allow clients
        -- to recognize heads from previous sessions and for example load head-
        -- specific configurations back.
        -- It is not guaranteed this event will be ever sent. A reason for that
        -- can be that the compositor does not have information about the serial
        -- number of the head or the definition of a serial number is not sensible
        -- in the current setup. Clients can still try to identify the head by
        -- available information from other events but should be aware that there
        -- is an increased risk of false positives.
        -- If sent, the serial number event is sent after a wlr_output_head object
        -- is created and only sent once per object. The serial number does not
        -- change over the lifetime of the wlr_output_head object.
        -- It is not recommended to display the serial_number string in UI to
        -- users. For that the string provided by the description event should be
        -- preferred.
        -- @event zwlr_output_head_v1:serial_number
        -- @tparam string serial_number
        {
            name = "serial_number",
            signature = "2s",
            types = { 0, },
        },
        --- current adaptive sync state
        --
        -- This event describes whether adaptive sync is currently enabled for
        -- the head or not. Adaptive sync is also known as Variable Refresh
        -- Rate or VRR.
        -- @event zwlr_output_head_v1:adaptive_sync
        -- @tparam uint state
        {
            name = "adaptive_sync",
            signature = "4u",
            types = { 0, },
        },
    },
    enums = {
        --- adaptive_sync_state
        -- @enum zwlr_output_head_v1.AdaptiveSyncState
        -- @param DISABLED 0 adaptive sync is disabled
        -- @param ENABLED 1 adaptive sync is enabled
        ["adaptive_sync_state"] = {
            ["disabled"] = 0,
            ["enabled"] = 1,
        },
    },
    methods_opcode = {
        ["release"] = 0,
    },
}

--- output mode
--
-- This object describes an output mode.
-- Some heads don't support output modes, in which case modes won't be
-- advertised.
-- Properties sent via this interface are applied atomically via the
-- wlr_output_manager.done event. No guarantees are made regarding the order
-- in which properties are sent.
-- @type zwlr_output_mode_v1
wau.zwlr_output_mode_v1:init {
    name = "zwlr_output_mode_v1",
    version = 3,
    methods = {
        --- destroy the mode object
        --
        -- This request indicates that the client will no longer use this mode
        -- object.
        -- @function zwlr_output_mode_v1:release
        -- @treturn zwlr_output_mode_v1 self
        {
            name = "release",
            signature = "3",
            types = { },
            type = "destructor"
        },
    },
    events = {
        --- mode size
        --
        -- This event describes the mode size. The size is given in physical
        -- hardware units of the output device. This is not necessarily the same as
        -- the output size in the global compositor space. For instance, the output
        -- may be scaled or transformed.
        -- @event zwlr_output_mode_v1:size
        -- @tparam int width width of the mode in hardware units
        -- @tparam int height height of the mode in hardware units
        {
            name = "size",
            signature = "ii",
            types = { 0, 0, },
        },
        --- mode refresh rate
        --
        -- This event describes the mode's fixed vertical refresh rate. It is only
        -- sent if the mode has a fixed refresh rate.
        -- @event zwlr_output_mode_v1:refresh
        -- @tparam int refresh vertical refresh rate in mHz
        {
            name = "refresh",
            signature = "i",
            types = { 0, },
        },
        --- mode is preferred
        --
        -- This event advertises this mode as preferred.
        -- @event zwlr_output_mode_v1:preferred
        {
            name = "preferred",
            signature = "",
            types = { },
        },
        --- the mode has disappeared
        --
        -- This event indicates that the mode is no longer available. The mode
        -- object becomes inert. Clients should send a destroy request and release
        -- any resources associated with it.
        -- @event zwlr_output_mode_v1:finished
        {
            name = "finished",
            signature = "",
            types = { },
        },
    },
    enums = {
    },
    methods_opcode = {
        ["release"] = 0,
    },
}

--- output configuration
--
-- This object is used by the client to describe a full output configuration.
-- First, the client needs to setup the output configuration. Each head can
-- be either enabled (and configured) or disabled. It is a protocol error to
-- send two enable_head or disable_head requests with the same head. It is a
-- protocol error to omit a head in a configuration.
-- Then, the client can apply or test the configuration. The compositor will
-- then reply with a succeeded, failed or cancelled event. Finally the client
-- should destroy the configuration object.
-- @type zwlr_output_configuration_v1
wau.zwlr_output_configuration_v1:init {
    name = "zwlr_output_configuration_v1",
    version = 4,
    methods = {
        --- enable and configure a head
        --
        -- Enable a head. This request creates a head configuration object that can
        -- be used to change the head's properties.
        -- @function zwlr_output_configuration_v1:enable_head
        -- @treturn zwlr_output_configuration_head_v1
        -- @tparam zwlr_output_head_v1 head the head to be enabled
        {
            name = "enable_head",
            signature = "no",
            types = { wau.zwlr_output_configuration_head_v1, wau.zwlr_output_head_v1, },
        },
        --- disable a head
        --
        -- Disable a head.
        -- @function zwlr_output_configuration_v1:disable_head
        -- @tparam zwlr_output_head_v1 head the head to be disabled
        -- @treturn zwlr_output_configuration_v1 self
        {
            name = "disable_head",
            signature = "o",
            types = { wau.zwlr_output_head_v1, },
        },
        --- apply the configuration
        --
        -- Apply the new output configuration.
        -- In case the configuration is successfully applied, there is no guarantee
        -- that the new output state matches completely the requested
        -- configuration. For instance, a compositor might round the scale if it
        -- doesn't support fractional scaling.
        -- After this request has been sent, the compositor must respond with an
        -- succeeded, failed or cancelled event. Sending a request that isn't the
        -- destructor is a protocol error.
        -- @function zwlr_output_configuration_v1:apply
        -- @treturn zwlr_output_configuration_v1 self
        {
            name = "apply",
            signature = "",
            types = { },
        },
        --- test the configuration
        --
        -- Test the new output configuration. The configuration won't be applied,
        -- but will only be validated.
        -- Even if the compositor succeeds to test a configuration, applying it may
        -- fail.
        -- After this request has been sent, the compositor must respond with an
        -- succeeded, failed or cancelled event. Sending a request that isn't the
        -- destructor is a protocol error.
        -- @function zwlr_output_configuration_v1:test
        -- @treturn zwlr_output_configuration_v1 self
        {
            name = "test",
            signature = "",
            types = { },
        },
        --- destroy the output configuration
        --
        -- Using this request a client can tell the compositor that it is not going
        -- to use the configuration object anymore. Any changes to the outputs
        -- that have not been applied will be discarded.
        -- This request also destroys wlr_output_configuration_head objects created
        -- via this object.
        -- @function zwlr_output_configuration_v1:destroy
        -- @treturn zwlr_output_configuration_v1 self
        {
            name = "destroy",
            signature = "",
            types = { },
            type = "destructor"
        },
    },
    events = {
        --- configuration changes succeeded
        --
        -- Sent after the compositor has successfully applied the changes or
        -- tested them.
        -- Upon receiving this event, the client should destroy this object.
        -- If the current configuration has changed, events to describe the changes
        -- will be sent followed by a wlr_output_manager.done event.
        -- @event zwlr_output_configuration_v1:succeeded
        {
            name = "succeeded",
            signature = "",
            types = { },
        },
        --- configuration changes failed
        --
        -- Sent if the compositor rejects the changes or failed to apply them. The
        -- compositor should revert any changes made by the apply request that
        -- triggered this event.
        -- Upon receiving this event, the client should destroy this object.
        -- @event zwlr_output_configuration_v1:failed
        {
            name = "failed",
            signature = "",
            types = { },
        },
        --- configuration has been cancelled
        --
        -- Sent if the compositor cancels the configuration because the state of an
        -- output changed and the client has outdated information (e.g. after an
        -- output has been hotplugged).
        -- The client can create a new configuration with a newer serial and try
        -- again.
        -- Upon receiving this event, the client should destroy this object.
        -- @event zwlr_output_configuration_v1:cancelled
        {
            name = "cancelled",
            signature = "",
            types = { },
        },
    },
    enums = {
        --- error
        -- @enum zwlr_output_configuration_v1.Error
        -- @param ALREADY_CONFIGURED_HEAD 1 head has been configured twice
        -- @param UNCONFIGURED_HEAD 2 head has not been configured
        -- @param ALREADY_USED 3 request sent after configuration has been applied or tested
        ["error"] = {
            ["already_configured_head"] = 1,
            ["unconfigured_head"] = 2,
            ["already_used"] = 3,
        },
    },
    methods_opcode = {
        ["enable_head"] = 0,
        ["disable_head"] = 1,
        ["apply"] = 2,
        ["test"] = 3,
        ["destroy"] = 4,
    },
}

--- head configuration
--
-- This object is used by the client to update a single head's configuration.
-- It is a protocol error to set the same property twice.
-- @type zwlr_output_configuration_head_v1
wau.zwlr_output_configuration_head_v1:init {
    name = "zwlr_output_configuration_head_v1",
    version = 4,
    methods = {
        --- set the mode
        --
        -- This request sets the head's mode.
        -- @function zwlr_output_configuration_head_v1:set_mode
        -- @tparam zwlr_output_mode_v1 mode
        -- @treturn zwlr_output_configuration_head_v1 self
        {
            name = "set_mode",
            signature = "o",
            types = { wau.zwlr_output_mode_v1, },
        },
        --- set a custom mode
        --
        -- This request assigns a custom mode to the head. The size is given in
        -- physical hardware units of the output device. If set to zero, the
        -- refresh rate is unspecified.
        -- It is a protocol error to set both a mode and a custom mode.
        -- @function zwlr_output_configuration_head_v1:set_custom_mode
        -- @tparam int width width of the mode in hardware units
        -- @tparam int height height of the mode in hardware units
        -- @tparam int refresh vertical refresh rate in mHz or zero
        -- @treturn zwlr_output_configuration_head_v1 self
        {
            name = "set_custom_mode",
            signature = "iii",
            types = { 0, 0, 0, },
        },
        --- set the position
        --
        -- This request sets the head's position in the global compositor space.
        -- @function zwlr_output_configuration_head_v1:set_position
        -- @tparam int x x position in the global compositor space
        -- @tparam int y y position in the global compositor space
        -- @treturn zwlr_output_configuration_head_v1 self
        {
            name = "set_position",
            signature = "ii",
            types = { 0, 0, },
        },
        --- set the transform
        --
        -- This request sets the head's transform.
        -- @function zwlr_output_configuration_head_v1:set_transform
        -- @tparam int transform
        -- @treturn zwlr_output_configuration_head_v1 self
        {
            name = "set_transform",
            signature = "i",
            types = { 0, },
        },
        --- set the scale
        --
        -- This request sets the head's scale.
        -- @function zwlr_output_configuration_head_v1:set_scale
        -- @tparam fixed scale
        -- @treturn zwlr_output_configuration_head_v1 self
        {
            name = "set_scale",
            signature = "f",
            types = { 0, },
        },
        --- enable/disable adaptive sync
        --
        -- This request enables/disables adaptive sync. Adaptive sync is also
        -- known as Variable Refresh Rate or VRR.
        -- @function zwlr_output_configuration_head_v1:set_adaptive_sync
        -- @tparam uint state
        -- @treturn zwlr_output_configuration_head_v1 self
        {
            name = "set_adaptive_sync",
            signature = "4u",
            types = { 0, },
        },
    },
    events = {
    },
    enums = {
        --- error
        -- @enum zwlr_output_configuration_head_v1.Error
        -- @param ALREADY_SET 1 property has already been set
        -- @param INVALID_MODE 2 mode doesn't belong to head
        -- @param INVALID_CUSTOM_MODE 3 mode is invalid
        -- @param INVALID_TRANSFORM 4 transform value outside enum
        -- @param INVALID_SCALE 5 scale negative or zero
        -- @param INVALID_ADAPTIVE_SYNC_STATE 6 invalid enum value used in the set_adaptive_sync request
        ["error"] = {
            ["already_set"] = 1,
            ["invalid_mode"] = 2,
            ["invalid_custom_mode"] = 3,
            ["invalid_transform"] = 4,
            ["invalid_scale"] = 5,
            ["invalid_adaptive_sync_state"] = 6,
        },
    },
    methods_opcode = {
        ["set_mode"] = 0,
        ["set_custom_mode"] = 1,
        ["set_position"] = 2,
        ["set_transform"] = 3,
        ["set_scale"] = 4,
        ["set_adaptive_sync"] = 5,
    },
}

end
