#ifndef ACTIONS_H
#define ACTIONS_H

enum Action {
    ACTION_NONE,
    ACTION_SPAWN_SH,
    ACTION_CLOSE,
    ACTION_FOCUS_NEXT,
    ACTION_MOVE,
    ACTION_RESIZE,
    ACTION_EXIT,
    ACTION_FULLSCREEN,
    ACTION_TAG_INC,
    ACTION_WIN_TAG_INC,
    ACTION_TAG_DEC,
    ACTION_WIN_TAG_DEC,
    ACTION_TAG_SET,
    ACTION_WIN_TAG_SET,
};

#endif
